### ISSUE TITLE
Can we open a view at particular index ?

### ISSUE THREAD

**Issue by Arbaz6786** [vikrantsharma123/ios-inshorts-view#1]
In this demo the inshorts view is coming from 0 index. Can we make it happen that it will start as desired index?

i.e we have array of 6 objects and I wan to start the view as 3rd object as I can swipe up or next and swipe down for previous.

Regards,
Arbaz Shaikh

**Comment by vikrantsharma123** [comment]
I will check this and update.

**Comment by vikrantsharma123** [comment]
It is possible to set the value of the _currentItemIndex_ property as the initial desired index, before setting the datasource.

For example, in the demo, ViewController.m, viewDidLoad method:

`self.inshortsView = [[InshortsView alloc] initWithFrame:self.view.frame];`
`self.inshortsView.currentItemIndex = 2;`
`self.inshortsView.dataSource = self;`
`self.inshortsView.delegate = self;`
`[self.view addSubview:self.inshortsView];`

**Comment by Arbaz6786** [comment]
Thanks  it is working fine I was just setting it after the  [self.view addSubview:self.inshortsView]; . that was the issue.

Thanks for your help.

**Comment by vikrantsharma123** [comment]
Great. Thank you.
